[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  VITE_API_URL = "https://gudangmitra-production.up.railway.app/api"

# Redirect all routes to index.html for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
